# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\juanc\Desktop\Asistente de vision\UI\generic_selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 219)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.widget.setObjectName("widget")
        self.slider_1 = QtWidgets.QSlider(self.widget)
        self.slider_1.setGeometry(QtCore.QRect(40, 50, 391, 22))
        self.slider_1.setMinimum(-99)
        self.slider_1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_1.setObjectName("slider_1")
        self.slider_2 = QtWidgets.QSlider(self.widget)
        self.slider_2.setEnabled(True)
        self.slider_2.setGeometry(QtCore.QRect(40, 120, 391, 22))
        self.slider_2.setMinimum(1)
        self.slider_2.setSingleStep(2)
        self.slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_2.setInvertedAppearance(False)
        self.slider_2.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.slider_2.setObjectName("slider_2")
        self.text = QtWidgets.QLabel(self.widget)
        self.text.setGeometry(QtCore.QRect(40, 20, 121, 16))
        self.text.setObjectName("text")
        self.text2 = QtWidgets.QLabel(self.widget)
        self.text2.setGeometry(QtCore.QRect(40, 90, 121, 16))
        self.text2.setObjectName("text2")
        self.value_1 = QtWidgets.QLineEdit(self.widget)
        self.value_1.setGeometry(QtCore.QRect(460, 50, 113, 20))
        self.value_1.setObjectName("value_1")
        self.value_2 = QtWidgets.QLineEdit(self.widget)
        self.value_2.setGeometry(QtCore.QRect(460, 120, 113, 20))
        self.value_2.setObjectName("value_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setGeometry(QtCore.QRect(440, 170, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Select Kernel and C"))
        self.text.setText(_translate("Dialog", "TITLE_TEXT_1"))
        self.text2.setText(_translate("Dialog", "TITLE_TEXT_2"))
        self.value_1.setText(_translate("Dialog", "0"))
        self.value_2.setText(_translate("Dialog", "0"))
